name:                scheme-in-forty-eight-hours
version:             0.1.0.0
github:              "gowda/scheme-in-forty-eight-hours"
license:             BSD3
author:              "Basavanagowda Kanur"
maintainer:          "basavanagowda@gmail.com"
copyright:           "2021 Basavanagowda Kanur"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/gowda/scheme-in-forty-eight-hours#readme>

dependencies:
- base >= 4.7 && < 5
- parsec

library:
  source-dirs: src

executables:
  scheme-in-forty-eight-hours-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - scheme-in-forty-eight-hours

tests:
  scheme-in-forty-eight-hours-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hspec
    - scheme-in-forty-eight-hours
