on: [push]
name: build
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'
          enable-stack: true
      - name: Setup
        run: stack setup
      - name: Test
        run: stack test
